### PR TITLE
Fix `:einval` error with ERTS 10.5.x

### PR DESCRIPTION
**Pull request by rosacris**
This PR fixes an error when trying to write a metric using ERTS 10.5.x
It looks like something changed in the `inet` implementation at run-time level that makes sending a message with the binary header fail with `:einval`.
This PR changes the code to use `:gen_udp.send/4` instead, dropping the header concept from the connection structure and package module.

### CODE REVIEW

**Comment by slashmili** [comment]
@lexmag is there any plan to merge/adopt this PR in the upstream.

**Comment by whatyouhide** [comment]
Hey @rosacris, I'm not a maintainer of this package, sorry.

**Comment by odarriba** [comment]
Any updates on this? We rely on this lib and we can't upgrade ERTS :(

**Comment by odarriba** [comment]
@lexmag Is there any update on this?

**Comment by rosacris** [comment]
We ended up forking fluxter an merged this patch there. However, we ended up switching to ex_flux that seems to be more active.

**Comment by lexmag** [comment]
Hi folks, I'm sorry for the delayed fix.
The version 0.8.1 should address the issue.
I need to measure `gen_udp` usage impact to performance before applying this PR.

**Comment by lexmag** [comment]
The issue itself has been fixed long ago (via 8981fd8b5579794f1575cc56a7167f39ff87f832).
`:gen_udp` usage needs further performance measurements before merging.

**Pull request closed without merging**
